model: RandomForest
stages:
    train: True
    predict: False
feature_processing:
    drop_low_cor: []
    scale: True
hyperparams:
    n_estimators: 50
    random_state: 42
train_test_split:
    shuffle: False
    test_size: 0.2
    random_state: 42
pathes:
    train_data: 'data/heart_cleveland_upload.csv'
    test_data: './data/test_data.csv'
    output_data: 'output/prediction.csv'
    model_path: './models/rf.pkl'
    logger_path: './ml_project/logs/log.txt'